
services:
  devcontainer:
    build:
      # Set the context to the parent directory, so we can add `.tool-versions` to the container
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      MIX_ENV: dev
    volumes:
      - ../:/workspace/slax
    network_mode: service:db
    command: sleep infinity
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data: